algoritmo "semnome"
var
   mes1, mes2 :inteiro

inicio
   escreval("Digite o mes do ano")
   aleatorio 1, 12
   leia(mes1)
   leia(mes2)
   aleatorio off
   escreval("")
   escreval("Mes 1:", mes1)
   escreval("Mes 2:", mes2)
fimAlgoritmo
//Exemplos de codigo:
//Crie um jogo onde o computador vai sortear um número entre 1 e 5 o
//jogador vai tentar descobrir qual foi o valor sorteado.