Algoritmo "ConversorDeMoedas"
Var
   c, q: inteiro
   r, d: real
Inicio
      c <- 1
      Escreva("Quantas vezes voce quer converter? ")
      leia(q)
      Enquanto (C <= q) faca
               Escreva("Qual o valor em R$?" )
               leia(r)
               d <- r/5.68
               EscrevaL("O valor convertido e US$?", d:5:2)
               c <- c + 1
Fimenquanto
Fimalgoritmo