Algoritmo "dobro e terca"
Var
   n, dobro, terca: real
Inicio
      Escreva("Digite um número: ")
      leia(n)
      dobro <- n * 2
      terca <- n / 3
      escreval("O dobro de ", n, " é ", dobro)
      escreval("A terça de ", n, " é ", terca:2:5)
      




Fimalgoritmo

//Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666