Algoritmo "Media notas"
Var
   N1, N2, media : real
Inicio
      Escreva("Nota 1: ")
      leia(N1)
      Escreva("Nota 2: ")
      leia(N2)
      media <- (N1 + N2) /2
      Escreva("A media entre ", N1, " e ", N2," iqual a ", media:2:1)




Fimalgoritmo

// Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5